"""Optiland's own lens analyses, delegated: `OpticalSetup + SourceSpec -> numbers`.

CHE-226 (R16). The backend-provided half of two deliberately separate paths:

* **a native analysis generates its own rays** from the source description, inside
  the pinned solver, using that solver's field, pupil, wavelength and conjugate
  machinery. That is this module.
* **a `RayBundle`-derived measurement consumes rays exactly as supplied**, which is
  `measurements/spot.py`.

Both produce a spot. Neither is expressible as the other, and this module does not
reimplement any part of the other: it builds the lens, hands it to
`optiland.analysis.SpotDiagram`, and translates the numbers that come back. The
rays it measures are generated by the solver and are never seen by this project as
a `RayBundle` -- that is the whole difference between the two paths, and it is why
a caller who *has* rays must not come here.

Why a backend package holds a measurement
------------------------------------------
Because a backend is a **provider**, not an operation kind (CHE-224 / R15.1, and
`AGENTS.md`): package location follows who executes, `kind` states what happens to
physical state, and an operation has exactly one of each. A measurement executed by
Optiland therefore lives beside the trace executed by Optiland and needs no
`measurements/ -> backends/` edge, which is the edge the dependency allowlist does
not have and does not need.

What this path deliberately cannot do
--------------------------------------
**Infinite conjugate only.** `SourceSpec` already carries the predicate --
`object_at_infinity` -- and a finite-conjugate source is refused rather than
reinterpreted. This is a scope decision and not a physical claim about spot
diagrams: a spot diagram is not inherently an infinite-conjugate measurement, but
this project has exactly one landed angular-field construction path, and quietly
handing a point-source distance to the solver's `angle` field type would report a
spot for a different object than the one declared. Optiland 0.6.0 ships
`ObjectHeightField`, `ParaxialImageHeightField` and `RealImageHeightField` and this
module deliberately reaches for none of them: a second finite-conjugate encoding
beside `SourceSpec.object_distance_mm` is the ambiguity R16 removed from its own
scope.

**One field and one wavelength.** `system.build_lens` declares exactly the field
being traced and one primary wavelength, on purpose (see its docstring), so
`fields="all"` and `wavelengths="all"` below are literally "the one declared". That
is stated on the result as `fields_analyzed` / `wavelengths_analyzed` rather than
left for a caller to assume, because a multi-field `RmsSpotSizeVsField` is what
those arguments mean in Optiland's own documentation and is *not* what happens
here. Multi-field analysis needs a problem-schema change and is future work.

**No rendering.** `SpotDiagram.view()` is never called. The pinned version exposes
`centroid()`, `rms_spot_radius()`, `geometric_spot_radius()` and the per-field
`SpotData` arrays independently of plotting, and this project has no plotting
dependency to add.

**One callable per analysis, not one dispatcher.** The obvious alternative was
`run(setup, source, analysis_type=...)` with an enum. It does not fit the landed
catalog: `operations/catalog.py` carries one record per callable and
`tests/operations/test_catalog_signatures.py` derives each record's ports and
result from `inspect.signature`, so a return type that varies with an argument
cannot be described by one record -- and the alternative, an `operation_id` switch,
is what `test_catalog.py::test_question_5` forbids. A second analysis here is a
second function and a second record, which is additive rather than a schema change.

Units and precision
-------------------
Optiland lengths are millimetres; everything returned from here is metres, via the
one conversion this package already declares (`rays.NATIVE_LENGTH_M`). Arrays come
back on the host with the solver's own precision preserved (`rays._host`), so a
float32 or GPU analysis is not silently widened to look like a float64 host one.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Any

import numpy as np

from backends.optiland.rays import NATIVE_LENGTH_M, NATIVE_WAVELENGTH_M, _host
from backends.optiland.solver import (
    Execution,
    _require_keys,
    _resolve_execution,
    configure_execution,
)
from backends.optiland.system import build_lens
from problems import OpticalSetup, SourceSpec

__all__ = [
    "NATIVE_ANALYSIS",
    "NATIVE_SPOT_METRIC_DEFINITIONS",
    "NativeSpotAnalysis",
    "spot_diagram",
]

#: The pinned solver's own name for the analysis this module delegates to, so the
#: record says which implementation produced its numbers and a version bump that
#: renames or moves it fails loudly here rather than silently elsewhere.
NATIVE_ANALYSIS = "optiland.analysis.SpotDiagram"

#: What Optiland's three spot metrics are, **read from the pinned implementation**
#: rather than assumed from their names, because this project's own
#: `measurements.spot_diagram` states different choices for two of the three and a
#: consumer comparing the two numbers has to know that.
#:
#: Measured in 0.6.0 (`optiland/analysis/spot_diagram.py`):
#:
#: * intensity is used only to **select** rays (`mask = i_g > 0`, so vignetted rays
#:   are dropped) and never to weight a moment;
#: * `centroid()` is the unweighted arithmetic mean of the reference wavelength's
#:   intersections, and it does **not** consult `reference`;
#: * `rms_spot_radius()` and `geometric_spot_radius()` are taken about the centre
#:   the `reference` argument selects -- `chief_ray` by Optiland's own default,
#:   which is **not** the centroid the same object reports.
#:
#: **That last point is a trap and it is why these strings exist.** Off axis the
#: chief ray and the centroid are different points, so the radii are not moments
#: about `centroid_m`: measured on the R05 reference singlet at 5 degrees, the RMS
#: is 2.664e-6 m about the chief ray and 2.655e-6 m about the centroid, and the
#: geometric radius differs by 5%. A consumer that assumed "radius about the
#: reported centroid" would be wrong by a small, plausible amount -- so the record
#: carries `reference` beside the numbers and this dictionary says what it selects.
#:
#: The project's own measurement is about the intensity-weighted centroid and
#: weights the centroid and the RMS by `|a|^2`. With equal-amplitude rays -- which
#: an unapodized Optiland launch fan has, measured -- and `reference="centroid"`,
#: the two definitions coincide exactly; with the default they do not. That is the
#: only regime in which the two paths' numbers are comparable at all, and
#: `tests/backends/test_optiland_analysis.py` pins both halves of it.
NATIVE_SPOT_METRIC_DEFINITIONS: dict[str, str] = {
    "inclusion": "rays with native intensity > 0; vignetted rays are dropped from the data",
    "centroid_m": (
        "unweighted arithmetic mean of the included intersections at the reference "
        "wavelength; independent of the `reference` argument"
    ),
    "rms_radius_m": (
        "sqrt(mean(x^2 + y^2)) about the centre selected by `reference`, unweighted -- "
        "NOT necessarily about centroid_m"
    ),
    "geometric_radius_m": (
        "max(sqrt(x^2 + y^2)) about that same selected centre, unweighted"
    ),
}

#: Optiland's defaults for the three arguments this module passes through, pinned
#: here so the record can state what was used when a caller passed nothing.
_DEFAULT_DISTRIBUTION = "hexapolar"
_DEFAULT_COORDINATES = "local"
_DEFAULT_REFERENCE = "chief_ray"


@dataclass(frozen=True)
class NativeSpotAnalysis:
    """One native spot analysis: the intersections, the three metrics, the provenance.

    A class on rule 2 -- the public record a consumer reads back -- and separate
    from `measurements.SpotResult` for a reason that is not tidiness. The two carry
    numbers computed under *different declared definitions* (see
    `NATIVE_SPOT_METRIC_DEFINITIONS`), and one record type spanning both would need
    a field saying which set applied, i.e. it would be two records with a tag. It is
    also what the dependency allowlist permits: `backends/` has no edge to
    `measurements/`, and adding one so that two paths could share a dataclass would
    trade a real architectural property for a saved class.

    Every field is a plain number or a host array. No `Optic`, no `RealRays`, no
    `SpotData`, no millimetre.
    """

    #: `(N,)` intersections at the image surface, in metres, for the one analysed
    #: field and wavelength. Vignetted rays are already absent -- Optiland drops
    #: them -- which is why there is no per-row alignment with anything and no
    #: intensity mask to apply.
    x_m: Any
    y_m: Any

    #: `(N,)` the solver's own per-ray intensity weight for the included rays. A
    #: real weight and **not** an amplitude: `rays.OPTILAND_INTENSITY_RULE` states
    #: why converting one to the other is a modelling decision this project makes
    #: only where it declares it.
    intensity: Any

    #: The unweighted mean of the intersections. **The two radii below are not
    #: moments about this point unless `reference == "centroid"`** -- see
    #: `NATIVE_SPOT_METRIC_DEFINITIONS`, which is carried on this record for that
    #: reason.
    centroid_m: tuple[float, float]
    rms_radius_m: float
    geometric_radius_m: float

    wavelength_m: float

    #: The field this analysed, in degrees, as declared by the source. One pair,
    #: because one field is what the lens carries.
    field_angle_deg: tuple[float, float]

    #: The pupil sampling and coordinate arguments actually passed to the solver.
    num_rings: int
    distribution: str
    coordinates: str
    reference: str

    #: How many fields and wavelengths the analysis ran over. Both `1`, always, and
    #: recorded rather than implied: see the module docstring.
    fields_analyzed: int
    wavelengths_analyzed: int

    #: Which implementation produced these numbers, and at which version. The
    #: fixture metadata R16 asks for, on the artifact rather than in a test file.
    analysis: str
    optiland_version: str
    mode: str = "native"

    metric_definitions: dict[str, str] | None = None

    def __post_init__(self) -> None:
        """Refuse a record whose numbers cannot be what they claim to be.

        Thin, deliberately: this record's job is to carry a delegation's output, and
        re-deriving the metrics here to check them would be reimplementing the
        analysis this module exists not to reimplement. What is checked is what a
        translation error looks like -- a non-finite or negative radius, a
        disagreeing array length, an empty spot.
        """
        if self.metric_definitions is None:
            object.__setattr__(self, "metric_definitions", dict(NATIVE_SPOT_METRIC_DEFINITIONS))

        lengths = {name: np.shape(getattr(self, name)) for name in ("x_m", "y_m", "intensity")}
        if len(set(lengths.values())) != 1 or len(lengths["x_m"]) != 1:
            raise ValueError(
                f"x_m, y_m and intensity must be one agreeing (N,) each, got {lengths!r}"
            )
        if lengths["x_m"][0] == 0:
            raise ValueError(
                "the analysis returned no intersections, so there is no spot. Every "
                "generated ray was vignetted, or the analysis ran on an empty field set"
            )

        for name in ("rms_radius_m", "geometric_radius_m"):
            value = float(getattr(self, name))
            if not math.isfinite(value) or value < 0.0:
                raise ValueError(f"{name}={value!r} is not a finite non-negative radius in metres")
        if not math.isfinite(self.wavelength_m) or self.wavelength_m <= 0.0:
            raise ValueError(f"wavelength_m={self.wavelength_m!r} is not a positive wavelength")
        if not (self.fields_analyzed == 1 and self.wavelengths_analyzed == 1):
            raise ValueError(
                f"this path analyses exactly one field and one wavelength, got "
                f"{self.fields_analyzed} and {self.wavelengths_analyzed}. A lens carrying "
                "more than one of either did not come from build_lens"
            )


def _import_optiland_analysis() -> tuple[Any, str]:
    """`(optiland.analysis.SpotDiagram, version)`, imported inside the call that needs it.

    The same deferral every module in this package uses: importing
    `backends.optiland` must not import a solver, so that listing what this project
    can do costs neither optiland nor torch. The version comes back with the class
    rather than being read elsewhere, so the record cannot name one version and the
    numbers come from another.
    """
    import optiland
    from optiland.analysis import SpotDiagram

    return SpotDiagram, str(optiland.__version__)


def spot_diagram(
    setup: OpticalSetup,
    source: SourceSpec,
    *,
    num_rings: int,
    execution: Execution,
    distribution: str = _DEFAULT_DISTRIBUTION,
    coordinates: str = _DEFAULT_COORDINATES,
    reference: str = _DEFAULT_REFERENCE,
) -> NativeSpotAnalysis:
    """Run the pinned solver's own spot analysis on `setup` under `source`.

    The rays are generated **inside** Optiland from the field, pupil, wavelength and
    distribution the constructed lens carries. Nothing is launched by this project
    and no `RayBundle` exists anywhere in this call: a caller that already holds
    rays wants `measurements.spot_diagram`, which measures them as supplied.

    `sampling=` is deliberately not reused from `solver.trace`. That `Sampling`
    record requires a `reference_surface` choice between `image_surface` and
    `exit_pupil`, and this analysis reports at the image surface by construction --
    accepting the key and ignoring it would be the silent discard that record exists
    to prevent. `num_rings` is passed on its own, and is the solver's `num_rays`
    argument under this project's name for it: a ring count, not a ray count, when
    the distribution is hexapolar.

    `distribution`, `coordinates` and `reference` are passed through unvalidated, on
    purpose: they are the pinned solver's vocabulary, it refuses an unknown value
    itself, and a whitelist here would be a second source of truth that goes stale
    at the next version bump. Their pinned defaults are recorded on the result.

    **`reference` selects what the two radii are measured about**, and its default
    is the solver's -- the chief ray, which off axis is not the centroid this same
    call reports. The default is kept rather than "improved" to `centroid`, because
    a delegation that quietly changes the wrapped tool's default answers a different
    question than the tool does. `NATIVE_SPOT_METRIC_DEFINITIONS` states it and the
    result carries it.

    Parameters
    ----------
    setup
        The neutral optical configuration. Its `reference_wavelength_um` locates the
        exit pupil; what is analysed is `source.wavelength_um`.
    source
        The neutral illumination. **Must be an infinite-conjugate source**: a
        `field_angle_deg` read as a direction. A finite `object_distance_mm` is
        refused.
    num_rings
        Hexapolar ring count for the generated fan.
    execution
        Device and precision, through the same capability gate and the same
        process-global configuration as a trace.

    Raises:
        TypeError: `source` is not a `SourceSpec` -- most likely a `RayBundle`,
            which this path cannot take at all.
        NotImplementedError: the source is finite-conjugate, which this path does
            not support.
        ValueError: `num_rings` is below 1, or `execution` is misspelled or
            incomplete.
        ImportError: optiland is not installed.
    """
    if not isinstance(source, SourceSpec):
        raise TypeError(
            f"spot_diagram takes a SourceSpec as its second argument, got "
            f"{type(source).__name__}. A native analysis GENERATES its rays from a source "
            "declaration; an already-materialized RayBundle is measured by "
            "measurements.spot_diagram, which takes no system at all."
        )
    if not source.object_at_infinity:
        raise NotImplementedError(
            f"this analysis supports only infinite-conjugate angular sources, and the "
            f"source declares object_distance_mm={source.object_distance_mm!r}. At a finite "
            "distance a field angle is a POSITION, not a direction (problems.SourceSpec), so "
            "passing it to the solver's 'angle' field type would analyse a different object "
            "than the one declared -- silently, with a plausible spot. Trace the "
            "finite-conjugate source and measure the resulting bundle with "
            "measurements.spot_diagram instead."
        )
    if num_rings < 1:
        raise ValueError(
            f"num_rings={num_rings!r} must be at least 1; it is the hexapolar ring count "
            "the solver spells num_rays"
        )

    # The capability gate and the process-global state, before the solver enters the
    # process -- the same three calls in the same order as a trace, so an analysis and
    # a trace of the same setup cannot disagree about device or precision. The key
    # check is not optional: `Execution` is a `TypedDict` and disappears at run time,
    # so `{"device": "cpu", "precison": "fp64"}` is a perfectly good dict.
    _require_keys(execution, name="execution")
    device, precision, namespace = _resolve_execution(execution)
    configure_execution(device=device, precision=precision, namespace=namespace)

    lens = build_lens(setup, source)
    spot_diagram_class, optiland_version = _import_optiland_analysis()
    native = spot_diagram_class(
        lens,
        fields="all",
        wavelengths="all",
        num_rings=num_rings,
        distribution=distribution,
        coordinates=coordinates,
        reference=reference,
    )

    # `data[field][wavelength]`, and `build_lens` declares exactly one of each. The
    # indices are asserted through the record rather than assumed here: a lens with
    # a second field would silently report the first field's spot.
    fields_analyzed = len(native.data)
    wavelengths_analyzed = len(native.data[0]) if fields_analyzed else 0
    spot = native.data[0][0]

    centroid_x_mm, centroid_y_mm = native.centroid()[0]
    rms_mm = native.rms_spot_radius()[0][0]
    geometric_mm = native.geometric_spot_radius()[0][0]

    return NativeSpotAnalysis(
        x_m=_host(spot.x) * NATIVE_LENGTH_M,
        y_m=_host(spot.y) * NATIVE_LENGTH_M,
        intensity=_host(spot.intensity),
        centroid_m=(
            float(_host(centroid_x_mm)) * NATIVE_LENGTH_M,
            float(_host(centroid_y_mm)) * NATIVE_LENGTH_M,
        ),
        rms_radius_m=float(_host(rms_mm)) * NATIVE_LENGTH_M,
        geometric_radius_m=float(_host(geometric_mm)) * NATIVE_LENGTH_M,
        wavelength_m=source.wavelength_um * NATIVE_WAVELENGTH_M,
        field_angle_deg=source.field_angle_deg,
        num_rings=int(num_rings),
        distribution=distribution,
        coordinates=coordinates,
        reference=reference,
        fields_analyzed=fields_analyzed,
        wavelengths_analyzed=wavelengths_analyzed,
        analysis=NATIVE_ANALYSIS,
        optiland_version=optiland_version,
    )
