"""Render the coverage matrix, open-gate register and gap list from the ledger.

CHE-104 (M0.3). These three documents are *derived*, never written. The point of
the ledger is that there is one place a claim lives; a hand-written coverage
matrix beside it would be a second place, and the two would disagree within a
milestone -- which is the failure this whole ticket is about.

``tests/test_claim_ledger.py`` regenerates all three in memory and compares
against the committed copies, following the pattern
``tests/test_generated_artifacts.py`` established for the JSON schemas. It never
writes, so it cannot quietly repair a drift it was supposed to report.

Run: ``./run.sh python scripts/generate_validation_coverage.py``
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from verification.claim_ledger import (  # noqa: E402
    CLAIMS,
    GAPS,
    LEDGER_COMPONENTS,
    NO_VALIDATED_CLAIM,
    RANKING_CRITERION,
    ClaimKind,
    GateStatus,
    Oracle,
    OracleIndependence,
    claims_for,
    open_gates,
)
from verification.families import BenchmarkLayer  # noqa: E402
from verification.families.registry import FAMILIES  # noqa: E402

OUTPUT_DIR = ROOT / "benchmarks" / "validation"

#: Ranked worst-first, so the gap list reads as a queue.
SEVERITY_ORDER = ("critical", "high", "medium", "low")

_GENERATED = (
    "<!-- GENERATED by scripts/generate_validation_coverage.py from\n"
    "     src/verification/claim_ledger.py. Do not edit: tests/test_claim_ledger.py\n"
    "     regenerates this in memory and fails if the committed copy differs. -->\n"
)


def _cell(component: str, kind: ClaimKind) -> str:
    """One coverage-matrix cell, compressed to the distinction that matters.

    The distinction being drawn is not "tested / untested" -- almost everything
    is tested. It is whether anything INDEPENDENT decided the answer. A cell
    reading ``self`` is a component checked against our own code, which is
    exactly the state the repository has a standing rule against relying on.
    """
    entries = [c for c in claims_for(component) if c.kind is kind]
    if not entries:
        return "--"
    marks = []
    for claim in entries:
        if claim.gate_status is GateStatus.NOT_MET:
            marks.append("**FAIL**")
        elif claim.gate_status is GateStatus.NOT_MEASURED:
            # Checked before the no-oracle case: "declared and never executed" is
            # the more useful thing to say about a cell than "no oracle applies",
            # and a NOT_MEASURED claim usually has no oracle precisely because
            # nothing was measured.
            marks.append("declared")
        elif claim.gate_status is GateStatus.MEASURED_OFF_GATE:
            marks.append("off-gate")
        elif claim.oracle is Oracle.NONE:
            marks.append("n/a")
        elif claim.oracle_independence is OracleIndependence.SHARES_CODE:
            marks.append("self")
        elif claim.gate_status is GateStatus.CHARACTERIZED_NO_GATE:
            marks.append("char")
        else:
            marks.append("**ind**")
    return " / ".join(marks)


#: CHE-141 (M2.5). Read from the family registry rather than from the ledger:
#: ``layer`` is a required field on ``BenchmarkFamily`` and the ledger's Claim
#: has no such field, so projecting it through would have been a second copy of
#: one fact. The generator can read both sources; only one of them owns this.
_LAYER_TITLE = {
    BenchmarkLayer.QUALIFICATION: "A — qualification",
    BenchmarkLayer.NUMERICAL: "B — numerical realization and validity",
    BenchmarkLayer.SYSTEM: "C — system",
}

_LAYER_ORDER = (
    BenchmarkLayer.QUALIFICATION,
    BenchmarkLayer.NUMERICAL,
    BenchmarkLayer.SYSTEM,
)


def _layer_coverage() -> list[str]:
    """Component x layer, and the layer-C gates spelled out.

    The matrix above says what *decides* each claim. This says what each claim
    is *about*, which is the question "what supports this system claim" — and
    the shape it exists to make visible is a layer-C gate resting on a component
    that nothing qualifies at layer A.
    """
    families = sorted(FAMILIES.values(), key=lambda f: f.family_id)
    lines = [
        "## Coverage by layer — CHE-141 (M2.5)",
        "",
        "Generated from `src/verification/families/`. The B0-B4 category says "
        "what may *decide* a family; the layer says what is being *claimed*. "
        "Layer C is the only layer at which a claim about an optical system may "
        "be made; layers A and B are the evidence underneath it. See "
        "`docs/benchmark_design.md`.",
        "",
        "| Component | " + " | ".join(_LAYER_TITLE[x] for x in _LAYER_ORDER) + " |",
        "| -- | -- | -- | -- |",
    ]
    for component in LEDGER_COMPONENTS:
        cells = []
        for layer in _LAYER_ORDER:
            ids = [f.family_id for f in families if f.layer is layer and component in f.components]
            cells.append(", ".join(f"`{i}`" for i in ids) if ids else "--")
        lines.append(f"| `{component}` | " + " | ".join(cells) + " |")

    lines += [
        "",
        "### Layer-C gates",
        "",
        "Where the system claims currently stand. An unmet gate is a first-class "
        "state and is reported here rather than left in a note.",
        "",
        "| family | gate | metric | observed |",
        "| -- | -- | -- | -- |",
    ]
    for fam in families:
        if fam.layer is not BenchmarkLayer.SYSTEM:
            continue
        gate = fam.gate_disposition
        status = f"`{gate.status.value}`" if gate else "not declared"
        metric = f"`{gate.metric}`" if gate and gate.metric else "--"
        observed = f"{gate.observed:.4g}" if gate and gate.observed is not None else "--"
        lines.append(f"| `{fam.family_id}` | {status} | {metric} | {observed} |")
    lines.append("")
    return lines


def coverage_matrix() -> str:
    kinds = list(ClaimKind)
    lines = [
        "# Validation coverage matrix",
        "",
        _GENERATED,
        "Components x claim kinds. What each cell means:",
        "",
        "| Mark | Meaning |",
        "| -- | -- |",
        "| `**ind**` | gate met, decided by an oracle that shares no code with the thing tested |",
        "| `char` | measured and reported, no pass/fail threshold declared. Not a pass |",
        "| `self` | checked only against our own implementation. May not decide a gate |",
        "| `off-gate` | executed, result on record, but the required gate never re-checks it |",
        "| `declared` | asserted in the registry or capability table, never executed |",
        "| `**FAIL**` | gate declared and not met |",
        "| `n/a` | no oracle applies (structured-failure and convention-plumbing claims) |",
        "| `--` | nobody has asked |",
        "",
        "| Component | " + " | ".join(k.value for k in kinds) + " |",
        "| -- | " + " | ".join("--" for _ in kinds) + " |",
    ]
    for component in LEDGER_COMPONENTS:
        lines.append(f"| `{component}` | " + " | ".join(_cell(component, k) for k in kinds) + " |")
    lines += [
        "",
        f"{len(CLAIMS)} claims over {len(LEDGER_COMPONENTS)} components.",
        "",
        *_layer_coverage(),
        "## The cells that should be read first",
        "",
        "* `M_WAVE_CHROMATIX` forward accuracy is `self`. The ASM is checked against our",
        "  own float64 propagator built from Chromatix's own `kernel_propagate`, so it",
        "  verifies the carrier bookkeeping and cannot verify the propagation. Its",
        "  conservation cell is blank for the same reason: the energy ledger that closes",
        "  is the composed one, filed under `C_RAY_TO_WAVE`.",
        "* `C_RAY_TO_WAVE` forward accuracy carries both `**ind**` and `**FAIL**`. The",
        "  synthetic analytic cases pass; the real traced system does not, and the two",
        "  are separate claims on purpose.",
        "* `M_RAY_OPTILAND` forward accuracy is `**ind**` for a COMPOSED claim -- the",
        "  exactness limit runs wave -> rays -> trace -> wave, so it cannot isolate a",
        "  solver error the reconstruction undoes. It does refract, through a",
        "  plane-parallel slab; no curved refracting surface has an analytic oracle.",
        "* Nothing anywhere is `**ind**` for `convergence`. Every convergence result in",
        "  this repository is characterization.",
        "",
    ]
    if NO_VALIDATED_CLAIM:
        lines += ["## Components with no validated claim", ""]
        lines += [f"* `{c}` -- {why}" for c, why in sorted(NO_VALIDATED_CLAIM.items())]
        lines += [""]
    return "\n".join(lines)


def open_gate_register() -> str:
    gates = open_gates()
    lines = [
        "# Open gates",
        "",
        _GENERATED,
        "Every declared gate that is currently not met, with what it measures and why",
        "it is still open. This replaces `benchmarks/manifest.yaml`'s `gate_disposition`",
        "prose as the queryable form; the prose remains as the narrative.",
        "",
        "No gate here has been widened. That is the rule the repository operates under,",
        "and a register of unmet gates is what makes it checkable rather than aspirational.",
        "",
    ]
    if not gates:
        lines += ["No open gates.", ""]
        return "\n".join(lines)
    for claim in gates:
        # A ceiling gate ("must be below") and a floor gate ("must be above")
        # read opposite ways, and rendering both as observed/tolerance made the
        # floor case say "0.35x" where it means "3x short". The direction is
        # inferred from which side of the tolerance the observation failed on,
        # which is the only information available and is unambiguous for an
        # unmet gate.
        if claim.observed is None or not claim.tolerance:
            shortfall = "n/a"
        elif claim.observed > claim.tolerance:
            shortfall = f"{claim.observed / claim.tolerance:.2f}x over a ceiling"
        else:
            shortfall = f"{claim.tolerance / claim.observed:.2f}x short of a floor"
        lines += [
            f"## `{claim.component}` -- {claim.metric}",
            "",
            f"* **observed** `{claim.observed}` against a gate of "
            f"`{claim.tolerance}` -- {shortfall}",
            f"* **claim** {claim.claim}",
            f"* **oracle** {claim.oracle.value}, {claim.oracle_independence.value}",
            f"* **measured in** {claim.device}"
            + (f" / {claim.dtype}" if claim.dtype else "")
            + (f" / {claim.namespace}" if claim.namespace else ""),
            f"* **tolerance basis** {claim.tolerance_basis}",
            "* **evidence**",
        ]
        lines += [f"  * `{e}`" for e in claim.evidence]
        if claim.caveats:
            lines += ["* **notes**"]
            lines += [f"  * {c}" for c in claim.caveats]
        lines += [""]
    return "\n".join(lines)


def gap_list() -> str:
    lines = [
        "# Validation gap list",
        "",
        _GENERATED,
        "What is not established, ranked. This is the scope input for M1, M2 and M4:",
        "each entry names the milestone that owes it, so those scopes are traceable here",
        "rather than re-derived.",
        "",
        "## Ranking criterion",
        "",
        "```",
        RANKING_CRITERION.strip(),
        "```",
        "",
    ]
    for severity in SEVERITY_ORDER:
        entries = [g for g in GAPS if g.severity == severity]
        if not entries:
            continue
        lines += [f"## {severity} ({len(entries)})", ""]
        for gap in entries:
            lines += [
                f"### `{gap.component}` / {gap.kind.value} -- {gap.owner}",
                "",
                gap.gap,
                "",
                f"* **why {severity}** {gap.rationale}",
                "* **blocks** " + ", ".join(gap.blocks),
                "",
            ]
    lines += [
        "## Owners, rolled up",
        "",
        "| Milestone | Gaps |",
        "| -- | -- |",
    ]
    for owner in sorted({g.owner for g in GAPS}):
        count = sum(1 for g in GAPS if g.owner == owner)
        worst = min(
            (SEVERITY_ORDER.index(g.severity) for g in GAPS if g.owner == owner),
            default=len(SEVERITY_ORDER),
        )
        lines.append(f"| {owner} | {count} (worst: {SEVERITY_ORDER[worst]}) |")
    lines.append("")
    return "\n".join(lines)


ARTIFACTS = {
    "coverage_matrix.md": coverage_matrix,
    "open_gates.md": open_gate_register,
    "gap_list.md": gap_list,
}


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for name, render in ARTIFACTS.items():
        path = OUTPUT_DIR / name
        path.write_text(render())
        print(f"wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
