"""Render ``benchmarks/instances/FIXED-V1.yaml`` from the declared suite.

CHE-135 (M4.4). The manifest is the committed, versioned artifact; the selection
lives in ``verification/fixed_suite.py`` because the choice is the deliverable
and a reviewer needs it in one place. ``tests/test_fixed_suite.py`` re-renders in
memory and compares, so the two cannot disagree.

    ./run.sh python scripts/generate_fixed_suite_manifest.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from core.paths import repository_root
from verification.fixed_suite import FIXED_V1

__all__ = ["main", "render"]

HEADER = """\
# GENERATED by scripts/generate_fixed_suite_manifest.py from
# src/verification/fixed_suite.py. Do not edit.
#
# FIXED-V1: the canonical fixed suite, chosen rather than inherited (CHE-135).
# Every instance carries a positive justification; "because it already existed"
# is not one. Tier `required` is enrolled in the default gate; tier `extended`
# is expensive, GPU or long-running and opt-in.
#
# This file replaces what benchmarks/manifest.yaml's `levels:` block used to do.
"""


def render() -> str:
    return HEADER + yaml.safe_dump(
        FIXED_V1.as_manifest(), sort_keys=False, width=88, default_flow_style=False
    )


def main() -> int:
    root = repository_root()
    out = root / "benchmarks" / "instances" / "FIXED-V1.yaml"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(), encoding="utf-8")
    print(f"wrote {out.relative_to(root)} ({len(FIXED_V1.instances)} instances)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
